### Graph Theory and Adjacency Matrices: An In-Depth Tutorial

#### Mathematical Background

Graph theory is a field of mathematics focused on studying graphs, which are mathematical structures used to model pairwise relations between objects. A graph consists of vertices (nodes) and edges (links) connecting pairs of vertices.

#### Key Concepts in Graph Theory

1. **Vertices and Edges**:
    - **Vertices (or Nodes)**: The fundamental units of a graph, typically represented as dots or circles.
    - **Edges (or Links)**: Connections between vertices, represented as lines.

2. **Types of Graphs**:
    - **Undirected Graph**: Edges have no direction. An edge between vertices $u$ and $v$ is represented as $(u, v)$.
    - **Directed Graph (or Digraph)**: Edges have a direction. An edge from vertex $u$ to vertex $v$ is represented as $(u \rightarrow v)$.

3. **Degree of a Vertex**:
    - **Undirected Graph**: The degree of a vertex is the number of edges connected to it.
    - **Directed Graph**: The in-degree of a vertex is the number of incoming edges, and the out-degree is the number of outgoing edges.

4. **Paths and Cycles**:
    - **Path**: A sequence of vertices connected by edges.
    - **Cycle**: A path that starts and ends at the same vertex without repeating any edges or vertices.

5. **Connected Graph**:
    - **Undirected Graph**: A graph is connected if there is a path between any two vertices.
    - **Directed Graph**: A graph is strongly connected if there is a directed path from any vertex to every other vertex.

#### Adjacency Matrices

An adjacency matrix is a way to represent a graph using a square matrix. The elements of the matrix indicate whether pairs of vertices are adjacent or not.

1. **Undirected Graph**:
    - The adjacency matrix $\mathbf{A}$ for an undirected graph with $n$ vertices is an $n \times n$ matrix where:
      $$
      A_{ij} =
      \begin{cases}
      1 & \text{if there is an edge between vertices } i \text{ and } j \\
      0 & \text{otherwise}
      \end{cases}
      $$
    - The matrix is symmetric ($A_{ij} = A_{ji}$).

2. **Directed Graph**:
    - The adjacency matrix $\mathbf{A}$ for a directed graph with $n$ vertices is an $n \times n$ matrix where:
      $$
      A_{ij} =
      \begin{cases}
      1 & \text{if there is a directed edge from vertex } i \text{ to vertex } j \\
      0 & \text{otherwise}
      \end{cases}
      $$

#### Numerical Example

Consider a simple undirected graph with 4 vertices $ V = \{1, 2, 3, 4\} $ and edges $ E = \{(1, 2), (1, 3), (2, 4), (3, 4)\} $:

1. **Graph Representation**:
    - Vertices: $ V = \{1, 2, 3, 4\} $
    - Edges: $ E = \{(1, 2), (1, 3), (2, 4), (3, 4)\} $

2. **Adjacency Matrix**:

    $$
    \mathbf{A} =
    \begin{bmatrix}
    0 & 1 & 1 & 0 \\
    1 & 0 & 0 & 1 \\
    1 & 0 & 0 & 1 \\
    0 & 1 & 1 & 0
    \end{bmatrix}
    $$

    - $A_{12} = 1$ because there is an edge between vertices 1 and 2.
    - $A_{13} = 1$ because there is an edge between vertices 1 and 3.
    - $A_{24} = 1$ because there is an edge between vertices 2 and 4.
    - $A_{34} = 1$ because there is an edge between vertices 3 and 4.

For a directed graph with edges $ E = \{(1 \rightarrow 2), (1 \rightarrow 3), (2 \rightarrow 4), (3 \rightarrow 4)\} $:

1. **Adjacency Matrix**:

    $$
    \mathbf{A} =
    \begin{bmatrix}
    0 & 1 & 1 & 0 \\
    0 & 0 & 0 & 1 \\
    0 & 0 & 0 & 1 \\
    0 & 0 & 0 & 0
    \end{bmatrix}
    $$

    - $A_{12} = 1$ because there is a directed edge from vertex 1 to vertex 2.
    - $A_{13} = 1$ because there is a directed edge from vertex 1 to vertex 3.
    - $A_{24} = 1$ because there is a directed edge from vertex 2 to vertex 4.
    - $A_{34} = 1$ because there is a directed edge from vertex 3 to vertex 4.

#### Key Properties of Adjacency Matrices

1. **Sparsity**: For large graphs, the adjacency matrix is often sparse (many zeros), especially if the number of edges is much less than the square of the number of vertices.

2. **Symmetry**: The adjacency matrix of an undirected graph is symmetric.

3. **Degree of a Vertex**: The degree of vertex $i$ in an undirected graph is the sum of the entries in row $i$ (or column $i$), and in a directed graph, the out-degree is the sum of the entries in row $i$ and the in-degree is the sum of the entries in column $i$.

4. **Path Lengths**: Powers of the adjacency matrix can provide information about paths of different lengths. For example, the element $(i, j)$ of $\mathbf{A}^k$ gives the number of paths of length $k$ from vertex $i$ to vertex $j$.

#### Important Notes on Using Adjacency Matrices

- **Computational Efficiency**: Adjacency matrices are useful for algorithms that benefit from matrix operations, such as finding the number of paths between vertices and eigenvalue-based graph analysis.

- **Memory Usage**: For sparse graphs, adjacency lists (which only store edges) are often more memory-efficient compared to adjacency matrices.

- **Graph Algorithms**: Many graph algorithms, such as those for finding shortest paths (e.g., Dijkstra's algorithm) or detecting cycles, can be implemented using adjacency matrices or adjacency lists.

This tutorial provides a comprehensive overview of graph theory and adjacency matrices, demonstrating their importance and application in representing and analyzing graphs.


In [1]:
# Python Implementation of Graph Theory and Adjacency Matrices

import numpy as np

# Define the adjacency matrix for an undirected graph with 4 vertices
# Example undirected graph:
# Vertices: V = {1, 2, 3, 4}
# Edges: E = {(1, 2), (1, 3), (2, 4), (3, 4)}
undirected_adj_matrix = np.array([
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [0, 1, 1, 0]
])

print("Adjacency Matrix for Undirected Graph:")
print(undirected_adj_matrix)

# Define the adjacency matrix for a directed graph with 4 vertices
# Example directed graph:
# Vertices: V = {1, 2, 3, 4}
# Edges: E = {(1 -> 2), (1 -> 3), (2 -> 4), (3 -> 4)}
directed_adj_matrix = np.array([
    [0, 1, 1, 0],
    [0, 0, 0, 1],
    [0, 0, 0, 1],
    [0, 0, 0, 0]
])

print("\nAdjacency Matrix for Directed Graph:")
print(directed_adj_matrix)

# Function to calculate the degree of each vertex in an undirected graph
def degree_undirected(adj_matrix):
    return np.sum(adj_matrix, axis=0)

# Function to calculate the in-degree and out-degree of each vertex in a directed graph
def degree_directed(adj_matrix):
    out_degree = np.sum(adj_matrix, axis=1)
    in_degree = np.sum(adj_matrix, axis=0)
    return in_degree, out_degree

# Calculate degrees for the undirected graph
undirected_degrees = degree_undirected(undirected_adj_matrix)
print("\nDegrees of vertices in Undirected Graph:", undirected_degrees)

# Calculate in-degrees and out-degrees for the directed graph
in_degrees, out_degrees = degree_directed(directed_adj_matrix)
print("\nIn-Degrees of vertices in Directed Graph:", in_degrees)
print("Out-Degrees of vertices in Directed Graph:", out_degrees)

# Function to calculate the number of paths of length k using adjacency matrix powers
def paths_of_length_k(adj_matrix, k):
    return np.linalg.matrix_power(adj_matrix, k)

# Calculate the number of paths of length 2 in the undirected graph
paths_length_2_undirected = paths_of_length_k(undirected_adj_matrix, 2)
print("\nNumber of paths of length 2 in Undirected Graph:")
print(paths_length_2_undirected)

# Calculate the number of paths of length 2 in the directed graph
paths_length_2_directed = paths_of_length_k(directed_adj_matrix, 2)
print("\nNumber of paths of length 2 in Directed Graph:")
print(paths_length_2_directed)


Adjacency Matrix for Undirected Graph:
[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 1]
 [0 1 1 0]]

Adjacency Matrix for Directed Graph:
[[0 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 0]]

Degrees of vertices in Undirected Graph: [2 2 2 2]

In-Degrees of vertices in Directed Graph: [0 1 1 2]
Out-Degrees of vertices in Directed Graph: [2 1 1 0]

Number of paths of length 2 in Undirected Graph:
[[2 0 0 2]
 [0 2 2 0]
 [0 2 2 0]
 [2 0 0 2]]

Number of paths of length 2 in Directed Graph:
[[0 0 0 2]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
