# Linear Algebra In-Depth Tutorial

## 2. Matrices

### Definition
A matrix is a rectangular array of numbers arranged in rows and columns.

### Notation
A matrix \( A \) with \( m \) rows and \( n \) columns is written as:
$$ A = \begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} & a_{m2} & \cdots & a_{mn} \end{bmatrix} $$

### Operations

#### Matrix Addition
If \( A \) and \( B \) are matrices of the same dimensions, their sum \( A + B \) is:
$$ A + B = \begin{bmatrix} a_{11} + b_{11} & a_{12} + b_{12} & \cdots & a_{1n} + b_{1n} \\ a_{21} + b_{21} & a_{22} + b_{22} & \cdots & a_{2n} + b_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{m1} + b_{m1} & a_{m2} + b_{m2} & \cdots & a_{mn} + b_{mn} \end{bmatrix} $$

#### Scalar Multiplication
If \( c \) is a scalar and \( A \) is a matrix, the scalar multiple \( cA \) is:
$$ cA = \begin{bmatrix} c \cdot a_{11} & c \cdot a_{12} & \cdots & c \cdot a_{1n} \\ c \cdot a_{21} & c \cdot a_{22} & \cdots & c \cdot a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ c \cdot a_{m1} & c \cdot a_{m2} & \cdots & c \cdot a_{mn} \end{bmatrix} $$

#### Matrix Multiplication
If \( A \) is an \( m $\times$ n \) matrix and \( B \) is an \( n $\times$ p \) matrix, their product \( AB \) is an \( m $\times$ p \) matrix given by:
$$ (AB)_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj} $$

### Numerical Example
Consider the following matrices:
$$ A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}, \quad \text{and scalar } c = 2 $$

#### Matrix Addition
Adding matrices \( A \) and \( B \):
$$ A + B = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} + \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} = \begin{bmatrix} 1 + 5 & 2 + 6 \\ 3 + 7 & 4 + 8 \end{bmatrix} = \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix} $$

#### Scalar Multiplication
Multiplying matrix \( A \) by scalar \( c \):
$$ cA = 2 \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} = \begin{bmatrix} 2 \cdot 1 & 2 \cdot 2 \\ 2 \cdot 3 & 2 \cdot 4 \end{bmatrix} = \begin{bmatrix} 2 & 4 \\ 6 & 8 \end{bmatrix} $$

#### Matrix Multiplication
Multiplying matrices \( A \) and \( B \):
$$ AB = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} = \begin{bmatrix} 1 \cdot 5 + 2 \cdot 7 & 1 \cdot 6 + 2 \cdot 8 \\ 3 \cdot 5 + 4 \cdot 7 & 3 \cdot 6 + 4 \cdot 8 \end{bmatrix} = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix} $$


In [ ]:
# Importing numpy for numerical operations
import numpy as np

# Define matrices A and B, and scalar c
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
c = 2

# Matrix addition
addition = A + B

# Scalar multiplication
scalar_multiplication = c * A

# Matrix multiplication
matrix_multiplication = np.dot(A, B)

# Display results
print("Matrix Addition (A + B):\n", addition)
print("Scalar Multiplication (2 * A):\n", scalar_multiplication)
print("Matrix Multiplication (A * B):\n", matrix_multiplication)


Matrix Addition (A + B):
 [[ 6  8]
 [10 12]]
Scalar Multiplication (2 * A):
 [[2 4]
 [6 8]]
Matrix Multiplication (A * B):
 [[19 22]
 [43 50]]
