### Linear Transformations: An In-Depth Tutorial

#### Mathematical Background

Linear transformations are fundamental concepts in linear algebra and are used extensively in various fields such as computer graphics, machine learning, and physics.

A **linear transformation** $T$ from a vector space $V$ to a vector space $W$ is a function that satisfies two main properties for all vectors $\mathbf{u}, \mathbf{v} \in V$ and all scalars $c$:

1. **Additivity (or Superposition Principle):**
   $$
   T(\mathbf{u} + \mathbf{v}) = T(\mathbf{u}) + T(\mathbf{v})
   $$
2. **Homogeneity (or Scalar Multiplication):**
   $$
   T(c \mathbf{u}) = c T(\mathbf{u})
   $$

These properties ensure that the transformation $T$ preserves the structure of the vector space.

##### Matrix Representation of Linear Transformations

In finite-dimensional vector spaces, linear transformations can be represented using matrices. Suppose $T$ is a linear transformation from $\mathbb{R}^n$ to $\mathbb{R}^m$. Then there exists an $m \times n$ matrix $A$ such that for any vector $\mathbf{x} \in \mathbb{R}^n$, the transformation $T$ can be written as:

$$
T(\mathbf{x}) = A\mathbf{x}
$$

Here, $A$ is called the **transformation matrix** of $T$.

##### Example

Consider a linear transformation $T: \mathbb{R}^2 \to \mathbb{R}^2$ defined by:

$$
T\left(\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}\right) = \begin{bmatrix} 2 & 1 \\ 0 & 3 \end{bmatrix} \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}
$$

The matrix representation of $T$ is:

$$
A = \begin{bmatrix} 2 & 1 \\ 0 & 3 \end{bmatrix}
$$

Let's apply $T$ to a vector $\mathbf{x} = \begin{bmatrix} 1 \\ 2 \end{bmatrix}$:

$$
T\left(\begin{bmatrix} 1 \\ 2 \end{bmatrix}\right) = \begin{bmatrix} 2 & 1 \\ 0 & 3 \end{bmatrix} \begin{bmatrix} 1 \\ 2 \end{bmatrix} = \begin{bmatrix} 2 \cdot 1 + 1 \cdot 2 \\ 0 \cdot 1 + 3 \cdot 2 \end{bmatrix} = \begin{bmatrix} 4 \\ 6 \end{bmatrix}
$$

So, $T\left(\begin{bmatrix} 1 \\ 2 \end{bmatrix}\right) = \begin{bmatrix} 4 \\ 6 \end{bmatrix}$.

##### Properties of Linear Transformations

1. **Identity Transformation**: The identity transformation $I: V \to V$ is defined by $I(\mathbf{x}) = \mathbf{x}$ for all $\mathbf{x} \in V$. Its matrix representation is the identity matrix $I_n$.

2. **Zero Transformation**: The zero transformation $O: V \to V$ is defined by $O(\mathbf{x}) = \mathbf{0}$ for all $\mathbf{x} \in V$. Its matrix representation is the zero matrix.

3. **Inverse Transformation**: If $T: V \to W$ is a bijective linear transformation, then there exists an inverse transformation $T^{-1}: W \to V$ such that $T^{-1}(T(\mathbf{x})) = \mathbf{x}$ for all $\mathbf{x} \in V$ and $T(T^{-1}(\mathbf{y})) = \mathbf{y}$ for all $\mathbf{y} \in W$.

4. **Composition of Transformations**: If $T: U \to V$ and $S: V \to W$ are linear transformations, then the composition $S \circ T: U \to W$ defined by $(S \circ T)(\mathbf{u}) = S(T(\mathbf{u}))$ is also a linear transformation. The matrix representation of $S \circ T$ is the product of the matrices representing $S$ and $T$.

#### Numerical Example

Let's consider a more detailed numerical example to illustrate these concepts.

Suppose we have a linear transformation $T: \mathbb{R}^3 \to \mathbb{R}^2$ defined by the matrix:

$$
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
$$

We want to find the image of the vector $\mathbf{x} = \begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix}$ under the transformation $T$.

$$
T\left(\begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix}\right) = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix} \begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix} = \begin{bmatrix} 1 \cdot 1 + 2 \cdot 0 + 3 \cdot (-1) \\ 4 \cdot 1 + 5 \cdot 0 + 6 \cdot (-1) \end{bmatrix} = \begin{bmatrix} -2 \\ -2 \end{bmatrix}
$$

Thus, $T\left(\begin{bmatrix} 1 \\ 0 \\ -1 \end{bmatrix}\right) = \begin{bmatrix} -2 \\ -2 \end{bmatrix}$.

This example demonstrates how to apply a linear transformation to a vector using matrix multiplication.


In [1]:
import numpy as np

# Define the transformation matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Define the vector x
x = np.array([1, 0, -1])

# Perform the linear transformation
T_x = A.dot(x)

print("Transformation matrix A:")
print(A)
print("\nVector x:")
print(x)
print("\nTransformed vector T(x):")
print(T_x)


Transformation matrix A:
[[1 2 3]
 [4 5 6]]

Vector x:
[ 1  0 -1]

Transformed vector T(x):
[-2 -2]
