### Singular Value Decomposition (SVD): An In-Depth Tutorial

#### Mathematical Background

Singular Value Decomposition (SVD) is a powerful matrix factorization technique used in various applications such as signal processing, statistics, and machine learning.

The **Singular Value Decomposition** of an $m \times n$ matrix $A$ is a factorization of the form:

$$
A = U \Sigma V^T
$$

where:
- $U$ is an $m \times m$ orthogonal matrix,
- $\Sigma$ is an $m \times n$ diagonal matrix with non-negative real numbers on the diagonal,
- $V$ is an $n \times n$ orthogonal matrix, and
- $V^T$ denotes the transpose of $V$.

The diagonal entries of $\Sigma$ are known as the **singular values** of $A$. The columns of $U$ and $V$ are called the **left-singular vectors** and **right-singular vectors** of $A$, respectively.

##### Properties of SVD

1. **Orthogonality**: The matrices $U$ and $V$ are orthogonal, meaning $U^TU = I_m$ and $V^TV = I_n$, where $I_m$ and $I_n$ are the identity matrices of size $m$ and $n$, respectively.

2. **Singular Values**: The singular values on the diagonal of $\Sigma$ are sorted in descending order and are always non-negative.

3. **Rank**: The number of non-zero singular values gives the rank of the matrix $A$.

4. **Condition Number**: The condition number of $A$ is the ratio of the largest singular value to the smallest singular value.

5. **Norms**: The largest singular value is equal to the operator norm of $A$, and the Frobenius norm of $A$ can be computed from the singular values.

##### Important Notes on Using SVD

- **Dimensionality Reduction**: SVD is widely used for dimensionality reduction in techniques such as Principal Component Analysis (PCA). By truncating the smaller singular values, we can approximate the original matrix with lower dimensions, reducing computational complexity while preserving important features.
  
- **Data Compression**: In image processing, SVD is used for image compression. By keeping only the largest singular values and their corresponding vectors, we can store a compressed version of the image that retains most of the visual information.

- **Noise Reduction**: SVD helps in noise reduction by discarding components associated with smaller singular values, which often correspond to noise in the data.

- **Numerical Stability**: SVD is numerically stable and provides accurate results even for ill-conditioned matrices, where other decomposition methods might fail.

#### Numerical Example

Let's consider a numerical example to illustrate the Singular Value Decomposition.

Suppose we have a matrix $A$:

$$
A = \begin{bmatrix} 3 & 1 & 1 \\ -1 & 3 & 1 \end{bmatrix}
$$

To perform the SVD of $A$, we decompose it into $U$, $\Sigma$, and $V^T$.

1. **Compute $A^TA$ and $AA^T$**:

$$
A^TA = \begin{bmatrix} 3 & 1 & 1 \\ -1 & 3 & 1 \end{bmatrix}^T \begin{bmatrix} 3 & 1 & 1 \\ -1 & 3 & 1 \end{bmatrix} = \begin{bmatrix} 10 & 2 & 2 \\ 2 & 10 & 2 \\ 2 & 2 & 2 \end{bmatrix}
$$

$$
AA^T = \begin{bmatrix} 3 & 1 & 1 \\ -1 & 3 & 1 \end{bmatrix} \begin{bmatrix} 3 & -1 \\ 1 & 3 \\ 1 & 1 \end{bmatrix} = \begin{bmatrix} 11 & 1 \\ 1 & 11 \end{bmatrix}
$$

2. **Find the eigenvalues and eigenvectors**:

   - The eigenvalues of $A^TA$ are $\lambda_1 = 12$ and $\lambda_2 = 8$.
   - The eigenvalues of $AA^T$ are the same, $\lambda_1 = 12$ and $\lambda_2 = 8$.

3. **Construct $\Sigma$**:

$$
\Sigma = \begin{bmatrix} \sqrt{12} & 0 \\ 0 & \sqrt{8} \end{bmatrix} = \begin{bmatrix} 2\sqrt{3} & 0 \\ 0 & 2\sqrt{2} \end{bmatrix}
$$

4. **Construct $U$ and $V$ from the eigenvectors**:

   - The eigenvectors of $AA^T$ form the columns of $U$.
   - The eigenvectors of $A^TA$ form the columns of $V$.

After calculations, we get:

$$
U = \begin{bmatrix} \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\ \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \end{bmatrix}
$$

$$
V = \begin{bmatrix} \frac{1}{\sqrt{6}} & \frac{1}{\sqrt{6}} & \frac{2}{\sqrt{6}} \\ \frac{1}{\sqrt{3}} & -\frac{1}{\sqrt{3}} & 0 \\ \frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}} \end{bmatrix}
$$

Finally, the SVD of $A$ is given by:

$$
A = U \Sigma V^T
$$

This example demonstrates the process of performing Singular Value Decomposition on a given matrix.


In [1]:
import numpy as np

# Define the matrix A
A = np.array([[3, 1, 1],
              [-1, 3, 1]])

# Perform SVD
U, S, VT = np.linalg.svd(A)

# Convert the 1D array of singular values to a diagonal matrix
Sigma = np.zeros_like(A, dtype=float)
Sigma[:len(S), :len(S)] = np.diag(S)

# Output the results
print("Matrix A:")
print(A)
print("\nLeft Singular Vectors (U):")
print(U)
print("\nSingular Values (Σ):")
print(Sigma)
print("\nRight Singular Vectors (V^T):")
print(VT)

# Reconstructing A from U, Sigma, and VT
A_reconstructed = U @ Sigma @ VT
print("\nReconstructed Matrix A from SVD:")
print(A_reconstructed)


Matrix A:
[[ 3  1  1]
 [-1  3  1]]

Left Singular Vectors (U):
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Singular Values (Σ):
[[3.46410162 0.         0.        ]
 [0.         3.16227766 0.        ]]

Right Singular Vectors (V^T):
[[-4.08248290e-01 -8.16496581e-01 -4.08248290e-01]
 [-8.94427191e-01  4.47213595e-01  5.26260748e-16]
 [-1.82574186e-01 -3.65148372e-01  9.12870929e-01]]

Reconstructed Matrix A from SVD:
[[ 3.  1.  1.]
 [-1.  3.  1.]]
