### Orthogonality and Orthonormality: An In-Depth Tutorial

#### Mathematical Background

Orthogonality and orthonormality are fundamental concepts in linear algebra, with significant applications in vector spaces, matrix factorizations, and signal processing.

##### Orthogonality

Two vectors $\mathbf{u}$ and $\mathbf{v}$ in an inner product space are said to be **orthogonal** if their inner product is zero:

$$
\mathbf{u} \cdot \mathbf{v} = 0
$$

In the Euclidean space $\mathbb{R}^n$, the inner product is the dot product, so $\mathbf{u} \cdot \mathbf{v} = 0$ implies:

$$
\sum_{i=1}^n u_i v_i = 0
$$

Orthogonality generalizes to sets of vectors: a set of vectors $\{\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_k\}$ is said to be orthogonal if every pair of distinct vectors in the set is orthogonal.

##### Orthonormality

A set of vectors $\{\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_k\}$ is **orthonormal** if it is orthogonal and each vector has unit length:

$$
\|\mathbf{u}_i\| = 1 \quad \text{for all } i
$$

This means:

$$
\mathbf{u}_i \cdot \mathbf{u}_j = \begin{cases}
1 & \text{if } i = j \\
0 & \text{if } i \neq j
\end{cases}
$$

##### Properties of Orthogonal and Orthonormal Sets

1. **Linear Independence**: Any orthogonal (or orthonormal) set of non-zero vectors is linearly independent.
2. **Basis**: An orthonormal set that spans a vector space $V$ forms an orthonormal basis for $V$.
3. **Simplified Computations**: Orthonormal bases simplify computations involving projections, changes of basis, and matrix factorizations.

##### Orthogonal Matrices

A square matrix $Q$ is called an **orthogonal matrix** if its columns (or rows) form an orthonormal set. This implies:

$$
Q^T Q = Q Q^T = I
$$

where $I$ is the identity matrix. For an orthogonal matrix $Q$, its inverse is its transpose: $Q^{-1} = Q^T$.

##### Numerical Example

Consider the vectors $\mathbf{u} = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$ and $\mathbf{v} = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$ in $\mathbb{R}^3$.

- These vectors are orthogonal because:

$$
\mathbf{u} \cdot \mathbf{v} = 1 \cdot 0 + 0 \cdot 1 + 0 \cdot 0 = 0
$$

- These vectors are also orthonormal because their lengths are 1:

$$
\|\mathbf{u}\| = \sqrt{1^2 + 0^2 + 0^2} = 1
$$

$$
\|\mathbf{v}\| = \sqrt{0^2 + 1^2 + 0^2} = 1
$$

Now, let's consider the matrix:

$$
Q = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}
$$

- This is an orthogonal matrix because:

$$
Q^T Q = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix} = I
$$

##### Important Notes on Using Orthogonality and Orthonormality

- **Projections**: Orthogonal and orthonormal vectors are used to project vectors onto subspaces. If $\{\mathbf{u}_1, \mathbf{u}_2, \ldots, \mathbf{u}_k\}$ is an orthonormal basis for a subspace $W$, the projection of $\mathbf{v}$ onto $W$ is:

$$
\text{proj}_W(\mathbf{v}) = (\mathbf{v} \cdot \mathbf{u}_1) \mathbf{u}_1 + (\mathbf{v} \cdot \mathbf{u}_2) \mathbf{u}_2 + \cdots + (\mathbf{v} \cdot \mathbf{u}_k) \mathbf{u}_k
$$

- **Matrix Factorizations**: Orthogonal matrices are used in various matrix factorizations, such as QR decomposition and SVD, due to their stability and simplifying properties.

- **Least Squares Solutions**: Orthogonality is critical in finding least squares solutions to linear systems, particularly through the method of orthogonal projections.

This tutorial provides a comprehensive overview of orthogonality and orthonormality, demonstrating their importance and application in linear algebra.


In [1]:
import numpy as np

# Function to check orthogonality of two vectors
def are_orthogonal(u, v):
    dot_product = np.dot(u, v)
    return np.isclose(dot_product, 0)

# Function to check if a set of vectors is orthonormal
def is_orthonormal_set(vectors):
    for i in range(len(vectors)):
        for j in range(len(vectors)):
            dot_product = np.dot(vectors[i], vectors[j])
            if i == j:
                if not np.isclose(dot_product, 1):
                    return False
            else:
                if not np.isclose(dot_product, 0):
                    return False
    return True

# Function to construct an orthogonal matrix
def create_orthogonal_matrix(vectors):
    Q, R = np.linalg.qr(np.array(vectors).T)
    return Q.T

# Example vectors
u = np.array([1, 0, 0])
v = np.array([0, 1, 0])

# Check if u and v are orthogonal
print(f"Are vectors u and v orthogonal? {are_orthogonal(u, v)}")

# Example set of orthonormal vectors
vectors = [u, v, np.array([0, 0, 1])]

# Check if the set of vectors is orthonormal
print(f"Is the set of vectors orthonormal? {is_orthonormal_set(vectors)}")

# Create an orthogonal matrix from the set of vectors
orthogonal_matrix = create_orthogonal_matrix(vectors)
print("Orthogonal matrix from the set of vectors:")
print(orthogonal_matrix)

# Verify orthogonality of the matrix
print("Is the constructed matrix orthogonal? ", np.allclose(np.dot(orthogonal_matrix, orthogonal_matrix.T), np.eye(orthogonal_matrix.shape[0])))


Are vectors u and v orthogonal? True
Is the set of vectors orthonormal? True
Orthogonal matrix from the set of vectors:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Is the constructed matrix orthogonal?  True
